"""initial tables

Revision ID: 26802fcaa0dc
Revises: 
Create Date: 2025-11-24 12:21:22.857848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26802fcaa0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=600), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('ext', sa.String(length=20), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_index')
    # ### end Alembic commands ###
